# Generated by Django 5.2.3 on 2025-07-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMasterGroup',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tier', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('fit', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Product Master Group',
                'verbose_name_plural': 'Product Master Groups',
                'indexes': [models.Index(fields=['slug'], name='catalog_pro_slug_f8d801_idx'), models.Index(fields=['type'], name='catalog_pro_type_6a731b_idx'), models.Index(fields=['tier'], name='catalog_pro_tier_c8cf00_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('variant_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('color_name', models.CharField(db_index=True, max_length=50)),
                ('hex', models.CharField(max_length=7)),
                ('slug', models.SlugField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='catalog.productmastergroup')),
            ],
            options={
                'verbose_name': 'Color Variant',
                'verbose_name_plural': 'Color Variants',
            },
        ),
        migrations.CreateModel(
            name='SizeStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(db_index=True, max_length=4)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.colorgroup')),
            ],
            options={
                'verbose_name': 'Size Stock Price',
                'verbose_name_plural': 'Size Stock Prices',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(db_index=True, max_length=100)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.colorgroup')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'indexes': [models.Index(fields=['image_name'], name='catalog_pro_image_n_056295_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='colorgroup',
            index=models.Index(fields=['color_name'], name='catalog_col_color_n_1761a9_idx'),
        ),
        migrations.AddIndex(
            model_name='colorgroup',
            index=models.Index(fields=['slug'], name='catalog_col_slug_03b136_idx'),
        ),
        migrations.AddIndex(
            model_name='sizestockprice',
            index=models.Index(fields=['size'], name='catalog_siz_size_ef93dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sizestockprice',
            unique_together={('variant', 'size')},
        ),
    ]
