# Generated by Django 5.2.3 on 2025-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizestockprice',
            name='stripe_price_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Price ID (price_...) used at checkout.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sizestockprice',
            name='stripe_product_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Product ID (prod_...). Optional.', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='sizestockprice',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='ssp_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sizestockprice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ssp_price_gte_0'),
        ),
    ]
