# Generated by Django 5.2.3 on 2025-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmastergroup',
            name='brand_id',
            field=models.CharField(db_index=True, default='COVE', max_length=50),
        ),
        migrations.AddIndex(
            model_name='productmastergroup',
            index=models.Index(fields=['brand_id'], name='catalog_pro_brand_i_21e2a9_idx'),
        ),
    ]
