# Generated by Django 5.2.3 on 2025-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productmastergroup_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
