# Generated by Django 5.2.3 on 2025-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('theme_colors', models.JSONField(blank=True, help_text='Brand theme configuration (colors, fonts)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['brand_name'],
                'indexes': [models.Index(fields=['slug'], name='catalog_bra_slug_65677f_idx'), models.Index(fields=['is_active'], name='catalog_bra_is_acti_0ff477_idx')],
            },
        ),
    ]
