# Generated by Django 5.2.3 on 2025-12-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmastergroup',
            name='color_family',
            field=models.CharField(default='neutral', help_text='Color family: neutral, warm, cool, bold', max_length=20),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='featured',
            field=models.BooleanField(default=False, help_text='Featured product for promotions'),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='formality_score',
            field=models.IntegerField(default=5, help_text='Formality level 1-10 (1=gym, 10=black tie)'),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Product availability'),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='pattern',
            field=models.CharField(default='solid', help_text='Pattern type: solid, striped, graphic, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='season',
            field=models.JSONField(default=list, help_text="Suitable seasons: ['spring', 'summer', 'fall', 'winter']"),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='statement_piece',
            field=models.BooleanField(default=False, help_text='Is this a focal/statement piece?'),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='style_tags',
            field=models.JSONField(default=list, help_text="Style tags for outfit matching (e.g., ['minimalist', 'streetwear'])"),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='use_cases',
            field=models.JSONField(default=list, help_text="Use cases: ['casual', 'work', 'outdoor', etc.]"),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='versatility',
            field=models.IntegerField(default=5, help_text='Versatility score 1-10 (how many outfits can use this?)'),
        ),
    ]
