# Generated by Django 5.2.3 on 2026-01-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_outfit_builder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='affiliate_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage (e.g., 10.50 for 10.5%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='affiliate_network',
            field=models.CharField(blank=True, help_text='Affiliate network name: Awin, ShareASale, CJ, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='affiliate_program_id',
            field=models.CharField(blank=True, help_text='Program ID within the affiliate network', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='Custom API endpoint for product data', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='api_key_encrypted',
            field=models.CharField(blank=True, help_text='Encrypted API key for authentication', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(choices=[('direct', 'Direct Seller'), ('affiliate', 'Affiliate')], db_index=True, default='direct', help_text='Direct brands ship products; Affiliates redirect to external sites', max_length=20),
        ),
        migrations.AddField(
            model_name='brand',
            name='company_registration',
            field=models.CharField(blank=True, help_text='VAT/Business registration number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email for notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Primary contact person name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, help_text='ISO country code (DE, FR, IT, etc.)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='feed_url',
            field=models.URLField(blank=True, help_text='Product feed URL for automated sync', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='integration_method',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Upload'), ('api', 'API Integration'), ('shopify', 'Shopify Sync'), ('woocommerce', 'WooCommerce Sync'), ('affiliate_feed', 'Affiliate Feed')], db_index=True, default='manual', help_text='How brand uploads/syncs product data', max_length=20),
        ),
        migrations.AddField(
            model_name='brand',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last successful data sync timestamp', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When brand completed onboarding and went live', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Application Pending'), ('info_complete', 'Info Submitted'), ('products_added', 'Products Added'), ('live', 'Live on Platform'), ('suspended', 'Suspended')], db_index=True, default='pending', help_text='Current onboarding progress stage', max_length=20),
        ),
        migrations.AddField(
            model_name='brand',
            name='payment_method_verified',
            field=models.BooleanField(default=False, help_text='Whether Stripe Connect setup is complete'),
        ),
        migrations.AddField(
            model_name='brand',
            name='ships_from_country',
            field=models.CharField(blank=True, help_text='Primary shipping origin country (ISO code)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID for payouts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='sync_error_log',
            field=models.TextField(blank=True, help_text='Log of last sync error if failed', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='sync_frequency',
            field=models.CharField(choices=[('manual', 'Manual Only'), ('hourly', 'Every Hour'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', help_text='How often to automatically sync product data', max_length=20),
        ),
        migrations.AddField(
            model_name='brand',
            name='sync_status',
            field=models.CharField(choices=[('never', 'Never Synced'), ('success', 'Success'), ('pending', 'In Progress'), ('failed', 'Failed')], db_index=True, default='never', help_text='Current sync status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_type'], name='catalog_bra_brand_t_7faadc_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['integration_method'], name='catalog_bra_integra_a86476_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['onboarding_status'], name='catalog_bra_onboard_b723a8_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['sync_status'], name='catalog_bra_sync_st_1e7006_idx'),
        ),
    ]
