# Generated by Django 5.2.3 on 2026-01-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_enhance_brand_model_for_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmastergroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('trashed', 'Trashed'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='productmastergroup',
            name='trashed_at',
            field=models.DateTimeField(blank=True, help_text='Time moved to bin', null=True),
        ),
    ]
