# Generated by Django 5.2.3 on 2026-01-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productmastergroup_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmastergroup',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='External link for affiliate products (redirects user instead of cart)', max_length=500, null=True),
        ),
    ]
