# Generated by Django 5.2.3 on 2025-07-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_checkoutcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutcart',
            name='user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
