# Generated by Django 5.2.3 on 2025-07-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_checkoutcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutcart',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
