# Generated by Django 5.2.3 on 2025-08-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_checkoutcart_user_email_order_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutcart',
            name='checkout_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session ID (cs_...)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='guest_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='size',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='user_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='variant_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='checkoutcart',
            index=models.Index(fields=['payment_intent_id'], name='orders_chec_payment_553599_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutcart',
            index=models.Index(fields=['checkout_session_id'], name='orders_chec_checkou_58c4da_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutcart',
            index=models.Index(fields=['clerk_user_id'], name='orders_chec_clerk_u_8dadb4_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutcart',
            index=models.Index(fields=['guest_session_id'], name='orders_chec_guest_s_8b67f9_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutcart',
            index=models.Index(fields=['variant_id', 'size'], name='orders_chec_variant_2c0c75_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutcart',
            index=models.Index(fields=['created_at'], name='orders_chec_created_024d66_idx'),
        ),
    ]
