# Generated by Django 5.2.3 on 2025-08-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_checkoutcart_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_decremented',
            field=models.BooleanField(default=False),
        ),
    ]
