# Generated by Django 5.2.3 on 2025-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
