# Generated by Django 5.2.3 on 2025-09-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_currency_order_shipping_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
