# Generated by Django 5.2.3 on 2025-12-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text="User identifier. Format: 'user_{clerk_id}' or 'anon_{session_id}'", max_length=255)),
                ('product_id', models.CharField(db_index=True, help_text="Product variant ID (e.g., 'CCH001')", max_length=50)),
                ('interaction_type', models.CharField(choices=[('view_item', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('begin_checkout', 'Begin Checkout'), ('add_payment_info', 'Add Payment Info'), ('add_shipping_info', 'Add Shipping Info'), ('purchase', 'Purchase'), ('search', 'Search')], db_index=True, help_text='Type of interaction (GA4-compatible)', max_length=20)),
                ('session_id', models.CharField(db_index=True, help_text='Session identifier for funnel analysis', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the interaction occurred')),
                ('time_on_page', models.IntegerField(blank=True, help_text='Time spent on product page (seconds)', null=True)),
                ('scroll_depth', models.IntegerField(blank=True, help_text='Page scroll depth (percentage 0-100)', null=True)),
                ('consent_given', models.BooleanField(default=False, help_text='Whether user gave tracking consent (GDPR)')),
                ('anonymized', models.BooleanField(default=True, help_text='Whether data is anonymized (default: True for privacy)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (AB variant, recommendation source, etc.)')),
            ],
            options={
                'verbose_name': 'User Interaction',
                'verbose_name_plural': 'User Interactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='idx_user_time'), models.Index(fields=['product_id', 'timestamp'], name='idx_product_time'), models.Index(fields=['interaction_type', 'timestamp'], name='idx_type_time'), models.Index(fields=['session_id', 'timestamp'], name='idx_session_time'), models.Index(fields=['user_id', 'product_id', 'interaction_type'], name='idx_user_product_type')],
                'constraints': [models.CheckConstraint(condition=models.Q(('scroll_depth__isnull', True), models.Q(('scroll_depth__gte', 0), ('scroll_depth__lte', 100)), _connector='OR'), name='valid_scroll_depth'), models.CheckConstraint(condition=models.Q(('time_on_page__isnull', True), ('time_on_page__gte', 0), _connector='OR'), name='valid_time_on_page')],
            },
        ),
    ]
