# Generated by Django 5.2.3 on 2025-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('item_similarity', 'Item-Item Similarity Matrix'), ('user_similarity', 'User-User Similarity Matrix'), ('matrix_factorization', 'Matrix Factorization Model')], db_index=True, help_text='Type of CF model', max_length=50)),
                ('version', models.IntegerField(default=1, help_text='Model version number (auto-incremented)')),
                ('model_data', models.BinaryField(help_text='Pickled model data (similarity matrix, mappings, etc.)')),
                ('metadata', models.JSONField(default=dict, help_text='Model training metadata (num_users, num_items, training_time, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this model was trained and saved')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this is the currently active model')),
                ('file_size_bytes', models.IntegerField(default=0, help_text='Size of pickled model in bytes')),
            ],
            options={
                'verbose_name': 'CF Model',
                'verbose_name_plural': 'CF Models',
                'db_table': 'cf_models',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='cf_models_model_t_c36f48_idx'), models.Index(fields=['-created_at'], name='cf_models_created_14225a_idx')],
            },
        ),
    ]
