# Generated by Django 5.2.3 on 2025-11-06 22:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('guest_session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(db_index=True, default='open', max_length=24)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tools_cart',
            },
        ),
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('request_json', models.JSONField(default=dict)),
                ('response_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tools.cart')),
            ],
            options={
                'db_table': 'tools_cart_event',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_id', models.CharField(db_index=True, max_length=32)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], db_index=True, max_length=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(blank=True, default='', max_length=160)),
                ('color_name', models.CharField(blank=True, default='', max_length=80)),
                ('image', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tools.cart')),
            ],
            options={
                'db_table': 'tools_cart_item',
                'unique_together': {('cart', 'variant_id', 'size')},
            },
        ),
    ]
