"""
Verifier MCP Agent
Verifies agent responses against ground truth (tools) and drives conversation forward.
"""

from typing import Dict, List, Any, Optional
import json
import os
import logging
from litellm import acompletion

log = logging.getLogger(__name__)

class VerifierAgent:
    """
    LLM-based Critic that verifies Draft Answers against Tool Outputs
    and generates follow-up suggestions.
    """
    
    def __init__(self):
        pass
        
    async def verify(self, query: str, draft_answer: str, context: Dict[str, Any], tool_outputs: Dict[str, Any]) -> Dict[str, Any]:
        """
        Verify the draft answer.
        
        Args:
            query: The original user query.
            draft_answer: The answer generated by the Agent.
            context: Session context (filters, history, user profile).
            tool_outputs: The raw output from tools (DB results, etc.).
            
        Returns:
            {
                "status": "PASS" | "FAIL" | "RETRY",
                "critique": str,
                "refined_answer": str (if FAIL, otherwise same as draft),
                "refined_query": str (if RETRY, a new query for the agent),
                "suggestions": List[str] (3 follow-up questions)
            }
        """
        system_prompt = self._build_prompt(context, tool_outputs)
        
        print(f"\n🔍 [VERIFIER] Verifying Query: '{query}'")
        print(f"📝 [VERIFIER] Draft Answer: '{draft_answer}'")
        print(f"📊 [VERIFIER] Ground Truth (Tools): {json.dumps(tool_outputs)}")
        
        try:
            # Use a fast model for verification to minimize latency
            model = os.getenv("VERIFIER_MODEL", "openrouter/openai/gpt-4o-mini")
            
            response = await acompletion(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"User Query: {query}\nDraft Answer: {draft_answer}"}
                ],
                api_key=os.getenv("OPENROUTER_API_KEY"),
                temperature=0.0,
                max_tokens=500,
                response_format={ "type": "json_object" },
                extra_headers={
                    "HTTP-Referer": "http://localhost:8000",
                    "X-Title": "COVE AI Verifier"
                }
            )
            
            content = response.choices[0].message.content.strip()
            if content.startswith("```json"):
                content = content.replace("```json", "").replace("```", "").strip()
                
            result = json.loads(content)
            
            # Sanity check
            if "status" not in result:
                result["status"] = "PASS"
            if "refined_answer" not in result:
                result["refined_answer"] = draft_answer
            if "suggestions" not in result:
                result["suggestions"] = []
                
            log.info(f"✅ [VERIFIER] Result: {result.get('status')} - {result.get('critique')}")
            return result
            
        except Exception as e:
            log.error(f"❌ [VERIFIER] Verification failed: {e}", exc_info=True)
            # Fail safe: Return original draft
            return {
                "status": "PASS",
                "critique": f"Verification failed: {str(e)}",
                "refined_answer": draft_answer,
                "suggestions": []
            }

    def _build_prompt(self, context: Dict, tool_outputs: Dict) -> str:
        """Construct the verification prompt."""
        
        return f"""You are the Quality Assurance Verifier for a Shopping Assistant AI.

Your Goal: Ensure the Agent's answer is TRUTHFUL, HELPFUL, and DRIVES ENGAGEMENT.

## INPUT DATA (Ground Truth)
Use these inputs as absolute facts.
1. **Tool Outputs** (What the database/search actually found):
{json.dumps(tool_outputs, indent=2)}

2. **Session Context** (Active filters & Profile):
{json.dumps(context, indent=2)}

## YOUR TASK
You are the final gatekeeper. Your job is to prevent "Stupid AI Mistakes" and ensure "Premium User Experience".

Review the "Draft Answer" provided by the user.

### 1. HALLUCINATION CHECK (Critical)
- **Compare** the Answer against the Tool Outputs.
- If Tool says "0 items found", the Answer MUST admit it. If it says "Here are items", it is LYING. -> **FAIL**
- If User asked for "Blue" but Tool returned "Red" (fallback), the Answer MUST explain the switch ("We didn't have Blue, so here is Red"). If it claims they are Blue, it is LYING. -> **FAIL**

### 2. CONTEXT CONSISTENCY
- Does the answer make sense given the `Session History`?
- If the user just said "No, I hate those", does the answer acknowledge that?

### 3. TONE & STYLE
- Is the answer helpful, concise, and professional?
- **Avoid** robotic phrases like "I have queried the database".
- **Avoid** apologizing too much. Be confident.
- **NO MARKDOWN LINKS**. Never write [text](url). Just describe the product naturally.

### 4. DRIVE FORWARD (Engagement) - CRITICAL
Generate 3 UNIQUE, CONTEXT-AWARE follow-up suggestions based on the ACTUAL product found.
**BAD (generic)**: "Filter by size?", "Show cheaper options", "Different color?"
**GOOD (specific)**: 
- If product is $50 hoodie: "Show hoodies under $40?", "Black version available?", "XL in stock?"
- If product is blue dress: "Similar in red?", "Longer hem options?", "Matching heels?"
- If multiple items shown: "Compare the first two?", "Add the cheapest to cart?"

USE the tool_outputs (price, color, type) to generate SPECIFIC suggestions!

**USER PROFILE PERSONALIZATION**: If `user_profile` is in the Session Context, use it to personalize suggestions:
- If user prefers size XL: "Check XL availability?" instead of generic "Filter by size?"
- If user prefers color black: "Black version of this?" 
- If user shops in €50-100 range: "Similar under €80?"

### 4b. OUTFIT COMPLETENESS (Special Case)
If the tool_outputs contain outfit-related data (e.g., `missing_categories`, `budget_exceeded`, `is_outfit`):
- If categories are MISSING, suggest: "Try the Outfit Builder for more control"
- If budget was EXCEEDED, suggest: "Increase your budget?" or "Show just the bottoms?"
- Always acknowledge incomplete outfits honestly in refined_answer.

### 5. RETRY LOGIC (CRITICAL)
- If the tools found NO relevant items or the items completely miss the user's intent (e.g. searching 'red' but found 'blue'), and you believe a different search query would help, set status to 'RETRY'.
- Provide a 'refined_query' (e.g. 'navy blue hoodie') to guide the Agent.

## OUTPUT FORMAT (JSON)
Return a valid JSON object:
{{
  "status": "PASS" | "FAIL" | "RETRY",
  "critique": "Detailed explanation...",
  "refined_answer": "The corrected answer (if FAIL).",
  "refined_query": "New search query (only if RETRY)",
  "suggestions": ["Specific Question 1", "Specific Question 2", "Specific Question 3"]
}}

## RULES
- **Be ruthless**. If there is a 1% chance of hallucination, FAIL it.
- **No markdown links**. Write "Check out the COVE Hoodie for $50" NOT "[here](url)".
- **Suggestions MUST be product-specific**. Reference actual price/color/type from tool_outputs.
- **suggestions** must be under 6 words each.
"""

# Singleton instance
_verifier = None

def get_verifier() -> VerifierAgent:
    """Get or create singleton verifier"""
    global _verifier
    if _verifier is None:
        _verifier = VerifierAgent()
    return _verifier
