# Generated by Django 5.2.3 on 2025-11-23 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='chatsession',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chatsession',
            old_name='last_activity_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='meta',
        ),
        migrations.AddField(
            model_name='aiuserprofile',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Clerk user id, used when user object is not resolved yet.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='agent_kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='turn_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='cart_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_agent_kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiuserprofile',
            name='disliked_colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiuserprofile',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiuserprofile',
            name='preferred_colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiuserprofile',
            name='preferred_fit',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='aiuserprofile',
            name='style_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiuserprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='guest_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['clerk_user_id'], name='ai_profiles_clerk_u_c9ee2d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['guest_session_id'], name='ai_profiles_guest_s_7995cf_idx'),
        ),
    ]
