# Generated by Django 5.2.3 on 2025-12-06 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_profiles', '0002_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConversationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_session_id', models.CharField(blank=True, db_index=True, help_text='Anonymous session id from frontend (guestSessionId).', max_length=128)),
                ('clerk_user_id', models.CharField(blank=True, db_index=True, help_text='Clerk user id if logged in.', max_length=128)),
                ('email', models.EmailField(blank=True, help_text='Email if available at the time of the event.', max_length=254)),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], help_text="'user' or 'assistant'.", max_length=16)),
                ('kind', models.CharField(blank=True, help_text="High-level kind: 'question', 'answer', 'recommendations', 'size_fit', etc.", max_length=64)),
                ('content', models.TextField(help_text='Raw text that the user or assistant saw.')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Optional structured metadata (filters, items, cartId, etc.).')),
                ('source', models.CharField(default='cove-ai-core', help_text="Origin service, e.g. 'cove-ai-core', 'frontend', etc.", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guest_session_id', 'created_at'], name='ai_profiles_guest_s_e0e121_idx'), models.Index(fields=['clerk_user_id', 'created_at'], name='ai_profiles_clerk_u_117a26_idx')],
            },
        ),
    ]
