# Generated by Django 5.2.3 on 2026-01-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0003_aiconversationevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiuserprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("unisex", "Unisex")],
                help_text="User's gender preference for product recommendations",
                max_length=16,
                null=True,
            ),
        ),
    ]
